export enum FUNCTION {
  TIME_SERIES_INTRADAY = 'TIME_SERIES_INTRADAY',
  TIME_SERIES_DAILY = 'TIME_SERIES_DAILY',
  TIME_SERIES_DAILY_ADJUSTED = 'TIME_SERIES_DAILY_ADJUSTED',
  TIME_SERIES_WEEKLY = 'TIME_SERIES_WEEKLY',
  TIME_SERIES_WEEKLY_ADJUSTED = 'TIME_SERIES_WEEKLY_ADJUSTED',
  TIME_SERIES_MONTHLY = 'TIME_SERIES_MONTHLY',
  TIME_SERIES_MONTHLY_ADJUSTED = 'TIME_SERIES_MONTHLY_ADJUSTED',
  GLOBAL_QUOTE = 'GLOBAL_QUOTE',
  SYMBOL_SEARCH = 'SYMBOL_SEARCH',
  MARKET_STATUS = 'MARKET_STATUS'
}

export enum INTERVAL_INTRADAY {
  MIN = '1min',
  FIVE_MIN = '5min',
  FITEEN_MIN = '15min',
  THIRTY_MIN = '30min',
  HOUR = '60min'
}

export enum DATA_TYPE {
  JSON = 'json',
  CSV = 'csv'
}